### ISSUE TITLE
Is there any way to save jpg image with inferenced bounding box for record_frames sample?

### ISSUE THREAD

**Issue by lightlu** [intel/video-analytics-serving#82]
The gstreamer element jpegenc save each frame to jpg image naming by frame id for samples/record_frames. Is it possible to save the image with inferenced bounding box? Thank you

**Comment by whbruce** [comment]
@lightlu Note that this change to the pipeline exacerbates an existing timing issue that we hadn't noticed before. metapublish can create an mqtt message **before** the corresponding frame has been written so that [imread()](https://github.com/intel/video-analytics-serving/blob/master/samples/record_frames/mqtt_client.py#L37) can fail causing imshow() to throw due to loading a null image. A simple workaround is to wait for the frame to be written before reading it.
